#!/usr/bin/env php
<?php
/**
 * Recreate all themes with updated badge colors that match each theme
 */

require_once __DIR__ . '/../src/bootstrap.php';

use Hub\Database;

$db = Database::getInstance();
$pdo = $db->getConnection();

// Complete theme definitions with badge colors
$themes = [
    [
        'name' => 'Woodson Gold',
        'description' => 'Traditional school colors with gold accents',
        'is_system' => 1,
        'settings' => [
            // Main colors
            'primary_color' => '#C99700',
            'navbar_color' => '#000000',
            'background_color' => '#FFFFFF',
            'accent_color' => '#FFD700',
            
            // Header
            'header_bg_color' => '#000000',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#FFD700',
            
            // Sidebar
            'sidebar_bg' => '#FFFFFF',
            'sidebar_text_color' => '#374151',
            'sidebar_active_highlight' => '#FEF3C7',
            'sidebar_active_text_color' => '#C99700',
            'sidebar_hover_bg' => '#F9FAFB',
            
            // Buttons
            'button_primary_bg' => '#C99700',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#6B7280',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#C99700',
            
            // Role badges - gold theme
            'role_staff_bg' => '#FEF3C7',
            'role_staff_text' => '#92400E',
            'role_maintenance_bg' => '#FED7AA',
            'role_maintenance_text' => '#9A3412',
            'role_maintenance_director_bg' => '#FDBA74',
            'role_maintenance_director_text' => '#7C2D12',
            'role_manager_bg' => '#DDD6FE',
            'role_manager_text' => '#5B21B6',
            'role_admin_bg' => '#FCE7F3',
            'role_admin_text' => '#9F1239',
            'role_super_admin_bg' => '#FEE2E2',
            'role_super_admin_text' => '#991B1B',
            
            // Badge colors
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#6366F1',
            'badge_system_text' => '#FFFFFF',
            
            // Text colors
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#C99700',
            
            // Borders
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#C99700',
            
            // Backgrounds
            'bg_secondary' => '#F9FAFB',
            'bg_hover' => '#F3F4F6',
            'bg_active' => '#E5E7EB',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            
            // Status colors - Success
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            
            // Status colors - Danger
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            
            // Status colors - Warning
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            
            // Status colors - Info
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            
            // Scrollbar
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            
            // Shadows
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Newcastle Green',
        'description' => 'Kelly green and charcoal professional theme',
        'is_system' => 1,
        'settings' => [
            // Main colors - Charcoal primary, green accents
            'primary_color' => '#2C3E50',
            'navbar_color' => '#1A252F',
            'background_color' => '#FFFFFF',
            'accent_color' => '#00A650',
            
            // Header
            'header_bg_color' => '#1A252F',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#00A650',
            
            // Sidebar - green tinted
            'sidebar_bg' => '#F0F8F4',
            'sidebar_text_color' => '#2C3E50',
            'sidebar_active_highlight' => '#D1F2E0',
            'sidebar_active_text_color' => '#00733A',
            'sidebar_hover_bg' => '#E8F5EE',
            
            // Buttons
            'button_primary_bg' => '#2C3E50',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#00A650',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#00733A',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#00A650',
            
            // Role badges - green/charcoal theme
            'role_staff_bg' => '#D1F2E0',
            'role_staff_text' => '#00733A',
            'role_maintenance_bg' => '#B8E6CE',
            'role_maintenance_text' => '#004D27',
            'role_maintenance_director_bg' => '#00A650',
            'role_maintenance_director_text' => '#FFFFFF',
            'role_manager_bg' => '#34495E',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#2C3E50',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#1A252F',
            'role_super_admin_text' => '#00A650',
            
            // Badge colors
            'badge_success_bg' => '#00733A',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#2C3E50',
            'badge_system_text' => '#FFFFFF',
            
            // Text colors
            'text_primary' => '#1A252F',
            'text_secondary' => '#2C3E50',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#00A650',
            
            // Borders
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#00A650',
            
            // Backgrounds
            'bg_secondary' => '#F0F8F4',
            'bg_hover' => '#E8F5EE',
            'bg_active' => '#D1F2E0',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            
            // Status colors
            'success_bg' => '#D1F2E0',
            'success_text' => '#00733A',
            'success_border' => '#B8E6CE',
            'success_button' => '#00A650',
            'success_button_hover' => '#00733A',
            
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            
            // Scrollbar
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            
            // Shadows
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Ocean Blue',
        'description' => 'Calming blue tones with professional styling',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#2563EB',
            'navbar_color' => '#1E3A8A',
            'background_color' => '#FFFFFF',
            'accent_color' => '#60A5FA',
            'header_bg_color' => '#1E3A8A',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#60A5FA',
            'sidebar_bg' => '#EFF6FF',
            'sidebar_text_color' => '#1E3A8A',
            'sidebar_active_highlight' => '#DBEAFE',
            'sidebar_active_text_color' => '#1E40AF',
            'sidebar_hover_bg' => '#DBEAFE',
            'button_primary_bg' => '#2563EB',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#60A5FA',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#60A5FA',
            
            // Role badges - blue theme
            'role_staff_bg' => '#DBEAFE',
            'role_staff_text' => '#1E40AF',
            'role_maintenance_bg' => '#BFDBFE',
            'role_maintenance_text' => '#1E3A8A',
            'role_maintenance_director_bg' => '#93C5FD',
            'role_maintenance_director_text' => '#1E3A8A',
            'role_manager_bg' => '#60A5FA',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#3B82F6',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#2563EB',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#1E3A8A',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#2563EB',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#2563EB',
            'bg_secondary' => '#EFF6FF',
            'bg_hover' => '#DBEAFE',
            'bg_active' => '#BFDBFE',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Forest Green',
        'description' => 'Natural green tones for a fresh, organic feel',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#059669',
            'navbar_color' => '#064E3B',
            'background_color' => '#FFFFFF',
            'accent_color' => '#10B981',
            'header_bg_color' => '#064E3B',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#34D399',
            'sidebar_bg' => '#F0FDF4',
            'sidebar_text_color' => '#064E3B',
            'sidebar_active_highlight' => '#D1FAE5',
            'sidebar_active_text_color' => '#047857',
            'sidebar_hover_bg' => '#DCFCE7',
            'button_primary_bg' => '#059669',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#10B981',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#047857',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#10B981',
            
            // Role badges - green theme
            'role_staff_bg' => '#D1FAE5',
            'role_staff_text' => '#065F46',
            'role_maintenance_bg' => '#A7F3D0',
            'role_maintenance_text' => '#064E3B',
            'role_maintenance_director_bg' => '#6EE7B7',
            'role_maintenance_director_text' => '#064E3B',
            'role_manager_bg' => '#34D399',
            'role_manager_text' => '#064E3B',
            'role_admin_bg' => '#10B981',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#059669',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#047857',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#064E3B',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#059669',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#059669',
            'bg_secondary' => '#F0FDF4',
            'bg_hover' => '#DCFCE7',
            'bg_active' => '#BBF7D0',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D1FAE5',
            'success_text' => '#065F46',
            'success_border' => '#A7F3D0',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Sunset Orange',
        'description' => 'Warm orange and amber tones',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#EA580C',
            'navbar_color' => '#9A3412',
            'background_color' => '#FFFFFF',
            'accent_color' => '#FB923C',
            'header_bg_color' => '#9A3412',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#FED7AA',
            'sidebar_bg' => '#FFF7ED',
            'sidebar_text_color' => '#9A3412',
            'sidebar_active_highlight' => '#FFEDD5',
            'sidebar_active_text_color' => '#C2410C',
            'sidebar_hover_bg' => '#FED7AA',
            'button_primary_bg' => '#EA580C',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#FB923C',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#FB923C',
            
            // Role badges - orange theme
            'role_staff_bg' => '#FFEDD5',
            'role_staff_text' => '#9A3412',
            'role_maintenance_bg' => '#FED7AA',
            'role_maintenance_text' => '#7C2D12',
            'role_maintenance_director_bg' => '#FDBA74',
            'role_maintenance_director_text' => '#7C2D12',
            'role_manager_bg' => '#FB923C',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#F97316',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#EA580C',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#9A3412',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#EA580C',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#EA580C',
            'bg_secondary' => '#FFF7ED',
            'bg_hover' => '#FFEDD5',
            'bg_active' => '#FED7AA',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Royal Purple',
        'description' => 'Rich purple tones with elegant styling',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#7C3AED',
            'navbar_color' => '#5B21B6',
            'background_color' => '#FFFFFF',
            'accent_color' => '#A78BFA',
            'header_bg_color' => '#5B21B6',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#C4B5FD',
            'sidebar_bg' => '#FAF5FF',
            'sidebar_text_color' => '#5B21B6',
            'sidebar_active_highlight' => '#EDE9FE',
            'sidebar_active_text_color' => '#6D28D9',
            'sidebar_hover_bg' => '#DDD6FE',
            'button_primary_bg' => '#7C3AED',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#A78BFA',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#A78BFA',
            
            // Role badges - purple theme
            'role_staff_bg' => '#EDE9FE',
            'role_staff_text' => '#5B21B6',
            'role_maintenance_bg' => '#DDD6FE',
            'role_maintenance_text' => '#5B21B6',
            'role_maintenance_director_bg' => '#C4B5FD',
            'role_maintenance_director_text' => '#5B21B6',
            'role_manager_bg' => '#A78BFA',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#8B5CF6',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#7C3AED',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#5B21B6',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#7C3AED',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#7C3AED',
            'bg_secondary' => '#FAF5FF',
            'bg_hover' => '#EDE9FE',
            'bg_active' => '#DDD6FE',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Crimson Red',
        'description' => 'Bold red tones with strong presence',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#DC2626',
            'navbar_color' => '#991B1B',
            'background_color' => '#FFFFFF',
            'accent_color' => '#EF4444',
            'header_bg_color' => '#991B1B',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#FCA5A5',
            'sidebar_bg' => '#FEF2F2',
            'sidebar_text_color' => '#991B1B',
            'sidebar_active_highlight' => '#FEE2E2',
            'sidebar_active_text_color' => '#B91C1C',
            'sidebar_hover_bg' => '#FECACA',
            'button_primary_bg' => '#DC2626',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#EF4444',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#B91C1C',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#EF4444',
            
            // Role badges - red theme
            'role_staff_bg' => '#FEE2E2',
            'role_staff_text' => '#991B1B',
            'role_maintenance_bg' => '#FECACA',
            'role_maintenance_text' => '#991B1B',
            'role_maintenance_director_bg' => '#FCA5A5',
            'role_maintenance_director_text' => '#7F1D1D',
            'role_manager_bg' => '#F87171',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#EF4444',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#DC2626',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#991B1B',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#DC2626',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#DC2626',
            'bg_secondary' => '#FEF2F2',
            'bg_hover' => '#FEE2E2',
            'bg_active' => '#FECACA',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#FEE2E2',
            'danger_text' => '#991B1B',
            'danger_border' => '#FECACA',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Slate Gray',
        'description' => 'Professional neutral gray tones',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#475569',
            'navbar_color' => '#1E293B',
            'background_color' => '#FFFFFF',
            'accent_color' => '#64748B',
            'header_bg_color' => '#1E293B',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#CBD5E1',
            'sidebar_bg' => '#F8FAFC',
            'sidebar_text_color' => '#334155',
            'sidebar_active_highlight' => '#E2E8F0',
            'sidebar_active_text_color' => '#1E293B',
            'sidebar_hover_bg' => '#F1F5F9',
            'button_primary_bg' => '#475569',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#64748B',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#64748B',
            
            // Role badges - gray theme
            'role_staff_bg' => '#F1F5F9',
            'role_staff_text' => '#334155',
            'role_maintenance_bg' => '#E2E8F0',
            'role_maintenance_text' => '#334155',
            'role_maintenance_director_bg' => '#CBD5E1',
            'role_maintenance_director_text' => '#1E293B',
            'role_manager_bg' => '#94A3B8',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#64748B',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#475569',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#1E293B',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#475569',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#475569',
            'bg_secondary' => '#F8FAFC',
            'bg_hover' => '#F1F5F9',
            'bg_active' => '#E2E8F0',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Midnight Navy',
        'description' => 'Deep navy blue with sophisticated styling',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#1E3A8A',
            'navbar_color' => '#0F172A',
            'background_color' => '#FFFFFF',
            'accent_color' => '#3B82F6',
            'header_bg_color' => '#0F172A',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#93C5FD',
            'sidebar_bg' => '#F0F9FF',
            'sidebar_text_color' => '#1E3A8A',
            'sidebar_active_highlight' => '#DBEAFE',
            'sidebar_active_text_color' => '#1E40AF',
            'sidebar_hover_bg' => '#E0F2FE',
            'button_primary_bg' => '#1E3A8A',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#3B82F6',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#3B82F6',
            
            // Role badges - navy theme
            'role_staff_bg' => '#DBEAFE',
            'role_staff_text' => '#1E40AF',
            'role_maintenance_bg' => '#BFDBFE',
            'role_maintenance_text' => '#1E3A8A',
            'role_maintenance_director_bg' => '#93C5FD',
            'role_maintenance_director_text' => '#1E3A8A',
            'role_manager_bg' => '#60A5FA',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#3B82F6',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#1E3A8A',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#0F172A',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#1E3A8A',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#1E3A8A',
            'bg_secondary' => '#F0F9FF',
            'bg_hover' => '#E0F2FE',
            'bg_active' => '#BAE6FD',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Teal Wave',
        'description' => 'Fresh teal and cyan tones',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#0D9488',
            'navbar_color' => '#115E59',
            'background_color' => '#FFFFFF',
            'accent_color' => '#14B8A6',
            'header_bg_color' => '#115E59',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#5EEAD4',
            'sidebar_bg' => '#F0FDFA',
            'sidebar_text_color' => '#115E59',
            'sidebar_active_highlight' => '#CCFBF1',
            'sidebar_active_text_color' => '#0F766E',
            'sidebar_hover_bg' => '#99F6E4',
            'button_primary_bg' => '#0D9488',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#14B8A6',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#14B8A6',
            
            // Role badges - teal theme
            'role_staff_bg' => '#CCFBF1',
            'role_staff_text' => '#115E59',
            'role_maintenance_bg' => '#99F6E4',
            'role_maintenance_text' => '#0F766E',
            'role_maintenance_director_bg' => '#5EEAD4',
            'role_maintenance_director_text' => '#115E59',
            'role_manager_bg' => '#2DD4BF',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#14B8A6',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#0D9488',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#115E59',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#0D9488',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#0D9488',
            'bg_secondary' => '#F0FDFA',
            'bg_hover' => '#CCFBF1',
            'bg_active' => '#99F6E4',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Rose Pink',
        'description' => 'Soft pink tones with feminine elegance',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#E11D48',
            'navbar_color' => '#9F1239',
            'background_color' => '#FFFFFF',
            'accent_color' => '#FB7185',
            'header_bg_color' => '#9F1239',
            'header_text_color' => '#FFFFFF',
            'header_subtitle_color' => '#FECDD3',
            'sidebar_bg' => '#FFF1F2',
            'sidebar_text_color' => '#9F1239',
            'sidebar_active_highlight' => '#FFE4E6',
            'sidebar_active_text_color' => '#BE123C',
            'sidebar_hover_bg' => '#FECDD3',
            'button_primary_bg' => '#E11D48',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#FB7185',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#DC2626',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#059669',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#FB7185',
            
            // Role badges - rose theme
            'role_staff_bg' => '#FFE4E6',
            'role_staff_text' => '#9F1239',
            'role_maintenance_bg' => '#FECDD3',
            'role_maintenance_text' => '#9F1239',
            'role_maintenance_director_bg' => '#FDA4AF',
            'role_maintenance_director_text' => '#881337',
            'role_manager_bg' => '#FB7185',
            'role_manager_text' => '#FFFFFF',
            'role_admin_bg' => '#F43F5E',
            'role_admin_text' => '#FFFFFF',
            'role_super_admin_bg' => '#E11D48',
            'role_super_admin_text' => '#FFFFFF',
            
            'badge_success_bg' => '#059669',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#9F1239',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#111827',
            'text_secondary' => '#374151',
            'text_muted' => '#6B7280',
            'text_disabled' => '#D1D5DB',
            'text_inverse' => '#FFFFFF',
            'link_color' => '#E11D48',
            'border_primary' => '#E5E7EB',
            'border_secondary' => '#D1D5DB',
            'border_light' => '#F3F4F6',
            'border_focus' => '#E11D48',
            'bg_secondary' => '#FFF1F2',
            'bg_hover' => '#FFE4E6',
            'bg_active' => '#FECDD3',
            'bg_modal_overlay' => 'rgba(0,0,0,0.5)',
            'bg_code' => '#1F2937',
            'success_bg' => '#D4EDDA',
            'success_text' => '#155724',
            'success_border' => '#C3E6CB',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#F8D7DA',
            'danger_text' => '#721C24',
            'danger_border' => '#F5C6CB',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#FFF3CD',
            'warning_text' => '#856404',
            'warning_border' => '#FFEEBA',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#D1ECF1',
            'info_text' => '#0C5460',
            'info_border' => '#BEE5EB',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#F1F1F1',
            'scrollbar_thumb' => '#888888',
            'scrollbar_thumb_hover' => '#555555',
            'shadow_light' => '0.1',
            'shadow_medium' => '0.2',
            'shadow_heavy' => '0.3',
        ]
    ],
    [
        'name' => 'Dark Professional',
        'description' => 'High-contrast dark mode theme',
        'is_system' => 1,
        'settings' => [
            'primary_color' => '#60A5FA',
            'navbar_color' => '#111827',
            'background_color' => '#1F2937',
            'accent_color' => '#93C5FD',
            'header_bg_color' => '#111827',
            'header_text_color' => '#F9FAFB',
            'header_subtitle_color' => '#93C5FD',
            'sidebar_bg' => '#1F2937',
            'sidebar_text_color' => '#D1D5DB',
            'sidebar_active_highlight' => '#374151',
            'sidebar_active_text_color' => '#60A5FA',
            'sidebar_hover_bg' => '#374151',
            'button_primary_bg' => '#3B82F6',
            'button_primary_text' => '#FFFFFF',
            'button_secondary_bg' => '#6B7280',
            'button_secondary_text' => '#FFFFFF',
            'button_danger_bg' => '#EF4444',
            'button_danger_text' => '#FFFFFF',
            'button_success_bg' => '#10B981',
            'button_success_text' => '#FFFFFF',
            'unsaved_changes_glow_color' => '#60A5FA',
            
            // Role badges - dark theme with bright colors
            'role_staff_bg' => '#1E3A8A',
            'role_staff_text' => '#BFDBFE',
            'role_maintenance_bg' => '#92400E',
            'role_maintenance_text' => '#FED7AA',
            'role_maintenance_director_bg' => '#C2410C',
            'role_maintenance_director_text' => '#FFEDD5',
            'role_manager_bg' => '#5B21B6',
            'role_manager_text' => '#DDD6FE',
            'role_admin_bg' => '#BE123C',
            'role_admin_text' => '#FECDD3',
            'role_super_admin_bg' => '#991B1B',
            'role_super_admin_text' => '#FCA5A5',
            
            'badge_success_bg' => '#10B981',
            'badge_success_text' => '#FFFFFF',
            'badge_system_bg' => '#3B82F6',
            'badge_system_text' => '#FFFFFF',
            
            'text_primary' => '#F9FAFB',
            'text_secondary' => '#E5E7EB',
            'text_muted' => '#9CA3AF',
            'text_disabled' => '#6B7280',
            'text_inverse' => '#111827',
            'link_color' => '#60A5FA',
            'border_primary' => '#374151',
            'border_secondary' => '#4B5563',
            'border_light' => '#1F2937',
            'border_focus' => '#60A5FA',
            'bg_secondary' => '#111827',
            'bg_hover' => '#374151',
            'bg_active' => '#4B5563',
            'bg_modal_overlay' => 'rgba(0,0,0,0.8)',
            'bg_code' => '#0F172A',
            'success_bg' => '#065F46',
            'success_text' => '#D1FAE5',
            'success_border' => '#047857',
            'success_button' => '#10B981',
            'success_button_hover' => '#059669',
            'danger_bg' => '#7F1D1D',
            'danger_text' => '#FECACA',
            'danger_border' => '#991B1B',
            'danger_button' => '#EF4444',
            'danger_button_hover' => '#DC2626',
            'warning_bg' => '#78350F',
            'warning_text' => '#FED7AA',
            'warning_border' => '#92400E',
            'warning_button' => '#F59E0B',
            'warning_button_hover' => '#D97706',
            'info_bg' => '#1E3A8A',
            'info_text' => '#BFDBFE',
            'info_border' => '#1E40AF',
            'info_button' => '#3B82F6',
            'info_button_hover' => '#2563EB',
            'scrollbar_track' => '#1F2937',
            'scrollbar_thumb' => '#4B5563',
            'scrollbar_thumb_hover' => '#6B7280',
            'shadow_light' => '0.3',
            'shadow_medium' => '0.4',
            'shadow_heavy' => '0.5',
        ]
    ]
];

try {
    // First, delete all existing themes
    $pdo->exec("DELETE FROM themes WHERE 1=1");
    echo "Cleared existing themes.\n\n";
    
    // Insert all themes
    $stmt = $pdo->prepare("
        INSERT INTO themes (name, slug, description, is_system, is_active, settings, created_at, updated_at)
        VALUES (:name, :slug, :description, :is_system, :is_active, :settings, NOW(), NOW())
    ");
    
    foreach ($themes as $index => $theme) {
        // Generate slug from name
        $slug = strtolower(str_replace(' ', '-', $theme['name']));
        
        // Only the first theme (Woodson Gold) should be active
        $isActive = ($index === 0) ? 1 : 0;
        
        $stmt->execute([
            ':name' => $theme['name'],
            ':slug' => $slug,
            ':description' => $theme['description'],
            ':is_system' => $theme['is_system'],
            ':is_active' => $isActive,
            ':settings' => json_encode($theme['settings'], JSON_PRETTY_PRINT)
        ]);
        
        echo "✓ Created: {$theme['name']} (slug: {$slug})" . ($isActive ? " [ACTIVE]" : "") . "\n";
    }
    
    echo "\n=== Theme Recreation Complete ===\n";
    echo "Created: " . count($themes) . " themes\n";
    echo "All themes now have properly themed badge colors!\n";
    
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}
