-- Themes System
-- Allows saving and loading complete theme configurations

CREATE TABLE IF NOT EXISTS themes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    settings JSON NOT NULL,
    is_active BOOLEAN DEFAULT FALSE,
    is_system BOOLEAN DEFAULT FALSE COMMENT 'System themes cannot be deleted',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    INDEX idx_slug (slug),
    INDEX idx_is_active (is_active),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default Woodson ISD theme
INSERT INTO themes (name, slug, description, settings, is_active, is_system, created_by) VALUES
('Woodson ISD Default', 'woodson-default', 'Classic Woodson ISD gold and black theme', 
JSON_OBJECT(
    'primary_color', '#C99700',
    'navbar_color', '#000000',
    'background_color', '#FFFFFF',
    'accent_color', '#FFD700',
    'header_bg_color', '#000000',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#FFD700',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#F3F4F6',
    'footer_text_color', '#6B7280',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#FFD700',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#374151',
    'sidebar_active_highlight', '#FEF3C7',
    'sidebar_active_text_color', '#C99700',
    'sidebar_hover_bg', '#F9FAFB',
    'button_primary_bg', '#C99700',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#6B7280',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#DC2626',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#059669',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#C99700'
), TRUE, TRUE, NULL)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Dark Mode Theme
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Dark Professional', 'dark-mode', 'Dark theme for reduced eye strain', 
JSON_OBJECT(
    'primary_color', '#60A5FA',
    'navbar_color', '#1F2937',
    'background_color', '#111827',
    'accent_color', '#3B82F6',
    'header_bg_color', '#1F2937',
    'header_text_color', '#F9FAFB',
    'header_subtitle_color', '#60A5FA',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#1F2937',
    'footer_text_color', '#9CA3AF',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#60A5FA',
    'sidebar_bg', '#1F2937',
    'sidebar_text_color', '#E5E7EB',
    'sidebar_active_highlight', '#374151',
    'sidebar_active_text_color', '#60A5FA',
    'sidebar_hover_bg', '#374151',
    'button_primary_bg', '#3B82F6',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#4B5563',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#EF4444',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#10B981',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#60A5FA'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- High Contrast Theme
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('High Contrast', 'high-contrast', 'Maximum contrast for accessibility', 
JSON_OBJECT(
    'primary_color', '#0000FF',
    'navbar_color', '#000000',
    'background_color', '#FFFFFF',
    'accent_color', '#0000FF',
    'header_bg_color', '#000000',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#FFFF00',
    'header_title_font', 'Arial',
    'header_subtitle_font', 'Arial',
    'header_title_font_size', '1.5',
    'header_subtitle_font_size', '1',
    'header_height', '90',
    'footer_height', '50',
    'footer_bg_color', '#000000',
    'footer_text_color', '#FFFFFF',
    'footer_text_size', '1',
    'logo_height', '100',
    'logo_height_mobile', '60',
    'logo_glow_enabled', '0',
    'logo_glow_color', '#FFFFFF',
    'sidebar_bg', '#000000',
    'sidebar_text_color', '#FFFFFF',
    'sidebar_active_highlight', '#0000FF',
    'sidebar_active_text_color', '#FFFF00',
    'sidebar_hover_bg', '#333333',
    'button_primary_bg', '#0000FF',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#666666',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#FF0000',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#00FF00',
    'button_success_text', '#000000',
    'unsaved_changes_glow_color', '#FFFF00'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Newcastle Blue & White
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Newcastle Blue', 'newcastle-blue', 'Newcastle ISD blue and white colors', 
JSON_OBJECT(
    'primary_color', '#003DA5',
    'navbar_color', '#002B73',
    'background_color', '#FFFFFF',
    'accent_color', '#0052CC',
    'header_bg_color', '#002B73',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#6CB4EE',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#F0F4F8',
    'footer_text_color', '#4A5568',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#6CB4EE',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#2D3748',
    'sidebar_active_highlight', '#E6F2FF',
    'sidebar_active_text_color', '#003DA5',
    'sidebar_hover_bg', '#F7FAFC',
    'button_primary_bg', '#003DA5',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#718096',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#E53E3E',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#38A169',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#003DA5'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Cardinal Red
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Cardinal Red', 'cardinal-red', 'Classic cardinal red and white theme', 
JSON_OBJECT(
    'primary_color', '#B71C1C',
    'navbar_color', '#8B0000',
    'background_color', '#FFFFFF',
    'accent_color', '#D32F2F',
    'header_bg_color', '#8B0000',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#FFCDD2',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#FFF5F5',
    'footer_text_color', '#6B7280',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#EF5350',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#374151',
    'sidebar_active_highlight', '#FFEBEE',
    'sidebar_active_text_color', '#B71C1C',
    'sidebar_hover_bg', '#FAFAFA',
    'button_primary_bg', '#B71C1C',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#6B7280',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#DC2626',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#059669',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#B71C1C'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Forest Green
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Forest Green', 'forest-green', 'Deep forest green and white theme', 
JSON_OBJECT(
    'primary_color', '#1B5E20',
    'navbar_color', '#0D3D14',
    'background_color', '#FFFFFF',
    'accent_color', '#2E7D32',
    'header_bg_color', '#0D3D14',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#A5D6A7',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#F1F8F4',
    'footer_text_color', '#4A5568',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#66BB6A',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#2D3748',
    'sidebar_active_highlight', '#E8F5E9',
    'sidebar_active_text_color', '#1B5E20',
    'sidebar_hover_bg', '#F7FAFC',
    'button_primary_bg', '#1B5E20',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#718096',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#E53E3E',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#38A169',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#1B5E20'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Royal Purple
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Royal Purple', 'royal-purple', 'Regal purple and gold theme', 
JSON_OBJECT(
    'primary_color', '#6A1B9A',
    'navbar_color', '#4A148C',
    'background_color', '#FFFFFF',
    'accent_color', '#8E24AA',
    'header_bg_color', '#4A148C',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#FFD700',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#F9F5FF',
    'footer_text_color', '#6B7280',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#BA68C8',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#374151',
    'sidebar_active_highlight', '#F3E5F5',
    'sidebar_active_text_color', '#6A1B9A',
    'sidebar_hover_bg', '#FAFAFA',
    'button_primary_bg', '#6A1B9A',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#6B7280',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#DC2626',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#059669',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#6A1B9A'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Burnt Orange
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Burnt Orange', 'burnt-orange', 'Warm burnt orange and charcoal theme', 
JSON_OBJECT(
    'primary_color', '#E65100',
    'navbar_color', '#BF360C',
    'background_color', '#FFFFFF',
    'accent_color', '#FF6F00',
    'header_bg_color', '#BF360C',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#FFB74D',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#FFF3E0',
    'footer_text_color', '#6B7280',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#FF9800',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#374151',
    'sidebar_active_highlight', '#FFF3E0',
    'sidebar_active_text_color', '#E65100',
    'sidebar_hover_bg', '#FAFAFA',
    'button_primary_bg', '#E65100',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#6B7280',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#DC2626',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#059669',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#E65100'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Navy & Silver
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Navy Silver', 'navy-silver', 'Professional navy blue and silver theme', 
JSON_OBJECT(
    'primary_color', '#1A237E',
    'navbar_color', '#0D1642',
    'background_color', '#FFFFFF',
    'accent_color', '#303F9F',
    'header_bg_color', '#0D1642',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#C0C0C0',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#F5F5F5',
    'footer_text_color', '#6B7280',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#9FA8DA',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#374151',
    'sidebar_active_highlight', '#E8EAF6',
    'sidebar_active_text_color', '#1A237E',
    'sidebar_hover_bg', '#FAFAFA',
    'button_primary_bg', '#1A237E',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#9E9E9E',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#DC2626',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#059669',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#1A237E'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Maroon & Gold
INSERT INTO themes (name, slug, description, settings, is_active, is_system) VALUES
('Maroon Gold', 'maroon-gold', 'Classic maroon and gold combination', 
JSON_OBJECT(
    'primary_color', '#800000',
    'navbar_color', '#5C0000',
    'background_color', '#FFFFFF',
    'accent_color', '#A52A2A',
    'header_bg_color', '#5C0000',
    'header_text_color', '#FFFFFF',
    'header_subtitle_color', '#FFD700',
    'header_title_font', 'Roboto',
    'header_subtitle_font', 'Roboto',
    'header_title_font_size', '1.3',
    'header_subtitle_font_size', '0.85',
    'header_height', '80',
    'footer_height', '40',
    'footer_bg_color', '#FFF8E7',
    'footer_text_color', '#6B7280',
    'footer_text_size', '0.875',
    'logo_height', '90',
    'logo_height_mobile', '50',
    'logo_glow_enabled', '1',
    'logo_glow_color', '#FFD700',
    'sidebar_bg', '#FFFFFF',
    'sidebar_text_color', '#374151',
    'sidebar_active_highlight', '#FFF8E7',
    'sidebar_active_text_color', '#800000',
    'sidebar_hover_bg', '#FAFAFA',
    'button_primary_bg', '#800000',
    'button_primary_text', '#FFFFFF',
    'button_secondary_bg', '#6B7280',
    'button_secondary_text', '#FFFFFF',
    'button_danger_bg', '#DC2626',
    'button_danger_text', '#FFFFFF',
    'button_success_bg', '#059669',
    'button_success_text', '#FFFFFF',
    'unsaved_changes_glow_color', '#800000'
), FALSE, TRUE)
ON DUPLICATE KEY UPDATE updated_at = CURRENT_TIMESTAMP;

-- Track active theme in site settings
INSERT INTO site_settings (setting_key, setting_value, setting_type, description) VALUES
('active_theme_id', '1', 'number', 'ID of currently active theme')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
